namespace UnikraftScanner.Client;
using UnikraftScanner.Client.Helpers;
using System.Text;
using System.Diagnostics;

public class GDBKraftkitFetcher : IUnikraftAppResourceFetchingStrategy
{
    public string KraftBinPath {get; init;}
    
    public string KraftHackScriptResourceFetchPath {get; init;}

    public GDBKraftkitFetcher(string kraftBinPath, string kraftHackScriptResourceFetcherPath)
    {
        KraftBinPath = kraftBinPath;
        KraftHackScriptResourceFetchPath = kraftHackScriptResourceFetcherPath;
    }
    public ResultUnikraftScanner<bool> ApplyStrategy(BincompatContext ctx)
    {
        
        const string kraftHackMsg = "KRAFT HACK SUCCESS";
        
        Directory.SetCurrentDirectory(ctx.AppPath);

        // ##target## can be --target <name> / --plat <p> --arch <a> tuple
        const string kraftbuildTemplateCmd = "build -g --no-cache --no-update --no-prompt --log-level trace --log-type basic";
        string debuggerCmd = $"--args {this.KraftBinPath}";
        Process kraftBuilder = new Process();
        kraftBuilder.StartInfo.FileName = "gdb";
        kraftBuilder.StartInfo.Arguments = $"{this.KraftBinPath} --silent";
        kraftBuilder.StartInfo.RedirectStandardOutput = true;
        kraftBuilder.StartInfo.RedirectStandardError = true;
        kraftBuilder.StartInfo.RedirectStandardInput = true;

        kraftBuilder.Start();

        // read start banner (for example "Reading symbols from ....")
        StringBuilder hackOutput = new(kraftBuilder.StandardOutput.ReadToEnd());

        kraftBuilder.StandardInput.WriteLine($"source {this.KraftHackScriptResourceFetchPath}");
        
        // read output generated by loading the script (example: Breakpoint 1 at 0xabcdef: file /go/src/kraftkit.sh/internal/cli/kraft/utils/rootfs.go, line 22)
        hackOutput.Append(kraftBuilder.StandardOutput.ReadToEnd());

        // pass the kraft parameters here together with the "Y" for answering the prompt
        // `project already configured, are you sure you want to rerun the configure step`
        //  when we need to configure again the app even though
        // a .config file already exists from a previous build
        // https://github.com/CSBonLaboratory/Unikraft-Scanner/issues/17
        kraftBuilder.StandardInput.WriteLine($"run {kraftbuildTemplateCmd} {ctx.KraftTarget} <<< Y");

        // now we wait until it finishes
        kraftBuilder.WaitForExit();

        // read kraft all output and errors (if any)
        string hackOutputFinal = kraftBuilder.StandardOutput.ReadToEnd();
        string hackErr = kraftBuilder.StandardError.ReadToEnd();

        if (!hackOutputFinal.Contains(kraftHackMsg) || kraftBuilder.ExitCode != 0)
        {
            return ResultUnikraftScanner<bool>.Failure(

                new ErrorUnikraftScanner<string>(
                    @$"Building Unikraft app at {Directory.GetCurrentDirectory()} using GDB optimization and command
                    `{kraftBuilder.StartInfo.Arguments}` did not hit the hacky breakpoint or exit code is {kraftBuilder.ExitCode}
                    stdout:{hackOutput.Append(hackOutputFinal).ToString()}
                    stderr:{hackErr}",
                    ErrorTypes.KraftBuildProblem
                )
            );
        }

        kraftBuilder.Close();

        return (ResultUnikraftScanner<bool>)true;
    }
}
