profiles:

  - name: "Carol-dev"
    mode: "local"
    logfile: "./coverage_logd.log"
    outfile: "./coverage_out.ansi"
    verbose: 1
    coverityAPI:
        firefoxPath: "/home/karakitay/Desktop/firefox/firefox"
        geckoPath: "/snap/bin/geckodriver"
        coverityProject: "Unikraft-Scanning"
        projectOverviewURL: "https://scan.coverity.com/projects/unikraft-scanning?tab=overview"
        scraperWaitSeconds : 10
        interceptorTimeoutSeconds : 60
        snapshotsViewId : 54994
        projectId : 15201
        defectsViewId : 57658