version: 1
profiles:
  - name: "Carol-dev"
    mode: "local"
    logfile: "./coverage_log.log"
    outfile: "./coverage_out.ansi"
    verbose: 1
    coverityAPI:
        firefoxPath: "/home/karakitay/Desktop/firefox/firefox"
        geckoPath: "/snap/bin/geckodriver"
        coverityProject: "Unikraft-Scanning"
        projectOverviewURL: "https://scan.coverity.com/projects/unikraft-scanning?tab=overview"
        scraperWaitSeconds : 300
        interceptorTimeoutSeconds : 300
        snapshotsViewId : 54994
        projectId : 15201
        defectsViewId : 57658
        uploadTokenEnv: "UK_COV_UPLOAD_TOKEN"
        recentSnapshotRetries : 4