# Version used for configuration file
version: 1

# Path to the log file
logfile: "./unikraft_scanner.log"

# Path to log file that stores preprocessing debug output after code instrumentation
preprocFile: "./unikraft_scanner_preproc.log"

# Path to the out file which will contain results from various operations such as global status listing and application coverage view
outfile: "./coverage_out"

# Level of verbosity for logging: 1 - DEBUG, 2 - INFO, 3 - WARNING, 4 - ERROR, 5 - CRITICAL
verbose: 1

unikraftCoverageDB:
  # Username is the same as the one in coverityAPI.userEmail


  # Password env var for authentication to the DB, it is reccomended to be saved in ~/.bashrc
  pass: REDACTED

  # IP env var for authentication to the DB, it is reccomended to be saved in ~/.bashrc
  ip: REDACTED

  port: REDACTED

# Various options used by the tool's web scraper for uploading builds and fetching defects to and from the Coverity platform
coverityAPI:

  # path where all Coverity local tools such as cov-build are located
  covSuitePath: "/usr/bin/cov-analysis-linux64-2023.6.2/bin/"

  # Firefox app path used by the scraper
  firefoxPath: "/home/karakitay/Desktop/firefox/"

  # Directory which contains the Gecko engine used by the scraper
  geckoPath: "/snap/bin/"

  installGecko: "N"

  # Name of the Coverity project. It should be the title of the project from the Overview landing page in Coverity
  projectName: "Unikraft-Scanning"

  # Link of the project overview page URL
  projectOverviewURL: "https://scan.coverity.com/projects/unikraft-scanning?tab=overview"

  # How many seconds does the scraper wait for web elements to appear in order to interact with them.
  scraperWaitSeconds : 300

  # How many seconds does the scraper wait for the right packages from Coverity. It used during defect fetching
  interceptorTimeoutSeconds : 300

  # The ammount of time the tool waits for the build to be analyzed = snapshotPollingSeconds * recentSnapshotRetries 
  # How many seconds does the tool wait for before polling the status of the upload operation to Coverity
  snapshotPollingSeconds : 60

  # How many polling operations does the tool execute
  recentSnapshotRetries : 15

  #' Environment variable used to store the secret Coverity upload API token.
  uploadTokenEnv: "REDACTED"

  #' Environment variable used to store email address of the user's Coverity account. Use the email address linked with Github if authentication was done this way
  userEmail: "REDACTED"


        